### ISSUE TITLE
Depend on upstream crates

### ISSUE THREAD

**Issue by crawford** [coreos/tailor#14]
Right now, several of the crates are being pulled from GitHub or my filesystem directly. We'll want to wait until local changes have been merged upstream.

**Comment by sdemos** [comment]
we should document the packages that this is true for and track the upstream prs in this issue.

**Comment by crawford** [comment]
It only applies to github-rs. There is https://github.com/mgattozzi/github-rs/pull/80 and one more follow-up PR. We'll then have to wait for a tagged release.
