### ISSUE TITLE
Add ability to specify a details link

### ISSUE THREAD

**Issue by arithx** [coreos/tailor#22]
If possible in the github message write, it would be really useful if we could use the details link to jump to a configurable URL (specified in the `tailor.yaml`).

For instance, in Ignition we could specify a link to the `CONTRIBUTING.md` file in the `tailor.yaml` and then when a tailor check fails there's a link (similar to how Travis links to it's build) to it.

**Comment by crawford** [comment]
The details link should always go to the explanation page. The user could add a URL to their description (though it wouldn't be a link). Do you still think this is necessary?

**Comment by arithx** [comment]
I agree, with the changes I don't think this is necessary any longer.
